export const ActionTypes = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_REQUEST_SUCCESS: "LOGIN_REQUEST_SUCCESS",
  LOGIN_REQUEST_FAILURE: "LOGIN_REQUEST_FAILURE",

  SIGN_UP_REQUEST: "SIGN_UP_REQUEST",
  SIGN_UP_REQUEST_SUCCESS: "SIGN_UP_SUCCESS",
  SIGN_UP_REQUEST_FAILURE: "SIGN_UP_REQUEST_FAILURE",

  LOGOUT_REQUEST: "LOGOUT_REQUEST",

  FIREBASE_AUTH_ACTIVE: "FIREBASE_AUTH_ACTIVE",
  FIREBASE_AUTH_INACTIVE: "FIREBASE_AUTH_INACTIVE",

  SET_ACTIVE_USER_TITLE: "SET_ACTIVE_USER_TITLE",

  DATE_NIGHTS_REQUEST: "DATE_NIGHTS_REQUEST",
  DATE_NIGHTS_REQUEST_SUCCESS: "DATE_NIGHTS_REQUEST_SUCCESS",
  DATE_NIGHTS_REQUEST_FAILURE: "DATE_NIGHTS_REQUEST_FAILURE",

  DATE_NIGHT_CREATE_REQUEST: "DATE_NIGHT_CREATE_REQUEST",
  DATE_NIGHT_CREATE_REQUEST_SUCCESS: "DATE_NIGHT_CREATE_REQUEST_SUCCESS",
  DATE_NIGHT_CREATE_REQUEST_FAILURE: "DATE_NIGHT_CREATE_REQUEST_FAILURE",

  DATE_NIGHT_DELETE_SUCCESS: "DATE_NIGHT_DELETE_SUCCESS"
};
