export const ActionTypes = {
  ACTIVE_USER_FETCH: "ACTIVE_USER_FETCH",
  ACTIVE_USER_FETCH_SUCCESS: "ACTIVE_USER_FETCH_SUCCESS",
  ACTIVE_USER_FETCH_FAILURE: "ACTIVE_USER_FETCH_FAILURE",

  ACTIVE_USER_UPDATE: "ACTIVE_USER_UPDATE",
  ACTIVE_USER_UPDATE_SUCCESS: "ACTIVE_USER_UPDATE_SUCCESS",
  ACTIVE_USER_UPDATE_FAILURE: "ACTIVE_USER_UPDATE_FAILURE",

  ACTIVE_USER_CREATE: "ACTIVE_USER_CREATE",
  ACTIVE_USER_CREATE_SUCCESS: "ACTIVE_USER_CREATE_SUCCESS",
  ACTIVE_USER_CREATE_FAILURE: "ACTIVE_USER_CREATE_FAILURE",

  AUTH_LOADING_STATE_CHANGE: "AUTH_LOADING_STATE_CHANGE",

  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_REQUEST_SUCCESS: "LOGIN_REQUEST_SUCCESS",
  LOGIN_REQUEST_FAILURE: "LOGIN_REQUEST_FAILURE",

  SIGN_UP_REQUEST: "SIGN_UP_REQUEST",
  SIGN_UP_REQUEST_SUCCESS: "SIGN_UP_SUCCESS",
  SIGN_UP_REQUEST_FAILURE: "SIGN_UP_REQUEST_FAILURE",

  LOGOUT_REQUEST: "LOGOUT_REQUEST",

  FIREBASE_AUTH_ACTIVE: "FIREBASE_AUTH_ACTIVE",
  FIREBASE_AUTH_INACTIVE: "FIREBASE_AUTH_INACTIVE",

  PASSWORD_RESET_REQUEST_LOADING: "PASSWORD_RESET_REQUEST_LOADING",
  PASSWORD_RESET_REQUEST_SUCCESS: "PASSWORD_RESET_REQUEST_SUCCESS",
  PASSWORD_RESET_REQUEST_FAILURE: "PASSWORD_RESET_REQUEST_FAILURE",

  CREATE_CUSTOMER: "CREATE_CUSTOMER",
  CREATE_CUSTOMER_SUCCESS: "CREATE_CUSTOMER_SUCCESS",
  CREATE_CUSTOMER_FAILURE: "CREATE_CUSTOMER_FAILURE",

  CUSTOMER_FETCH_LOADING: "CUSTOMER_FETCH_LOADING",
  CUSTOMER_FETCH_SUCCESS: "CUSTOMER_FETCH_SUCCESS",
  CUSTOMER_FETCH_FAILURE: "CUSTOMER_FETCH_FAILURE",

  UPDATE_CUSTOMER: "UPDATE_CUSTOMER",
  UPDATE_CUSTOMER_SUCCESS: "UPDATE_CUSTOMER_SUCCESS",
  UPDATE_CUSTOMER_FAILURE: "UPDATE_CUSTOMER_FAILURE",

  SAVE_SOURCE: "SAVE_SOURCE",
  SAVE_SOURCE_SUCCESS: "SAVE_SOURCE_SUCCESS",
  SAVE_SOURCE_FAILURE: "SAVE_SOURCE_FAILURE",

  ADD_TEMP_SOURCE: "ADD_TEMP_SOURCE",

  DELETE_SOURCE: "DELETE_SOURCE",
  DELETE_SOURCE_SUCCESS: "DELETE_SOURCE_SUCCESS",
  DELETE_SOURCE_FAILURE: "DELETE_SOURCE_FAILURE",

  PHONE_AUTH_REQUEST: "PHONE_AUTH_REQUEST",
  PHONE_AUTH_SUCCESS: "PHONE_AUTH_SUCCESS",
  PHONE_AUTH_FAILURE: "PHONE_AUTH_FAILURE",

  FETCH_SAVED_SOURCES: "FETCH_SAVED_SOURCES",
  FETCH_SAVED_SOURCES_SUCCESS: "FETCH_SAVED_SOURCES_SUCCESS",
  FETCH_SAVED_SOURCES_FAILURE: "FETCH_SAVED_SOURCES_FAILURE",

  CREATE_CHARGE: "CREATE_CHARGE",
  CREATE_CHARGE_SUCCESS: "CREATE_CHARGE_SUCCESS",
  CREATE_CHARGE_FAILURE: "CREATE_CHARGE_FAILURE",

  SAVE_POSITION: "SAVE_POSITION",
  SAVE_POSITION_SUCCESS: "SAVE_POSITION_SUCCESS",
  SAVE_POSITION_FAILURE: "SAVE_POSITION_FAILURE",

  VERIFY_PHONE_NUMBER_REQUEST: "VERIFY_PHONE_NUMBER_REQUEST",
  VERIFY_PHONE_NUMBER_SUCCESS: "VERIFY_PHONE_NUMBER_SUCCESS",
  VERIFY_PHONE_NUMBER_FAILURE: "VERIFY_PHONE_NUMBER_FAILURE"
};
